server:
  port:
    8080

spring:
  rabbitmq: # ++++++++++ Neu hinzugefügt fpr RPC ++++++++++++++++++++
    host: rabbitmq
#    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      reply-timeout: 5000 # 5 Sekunden Timeout für RPC-Antwort


